#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
    deb-systemd-invoke stop corepvt.timer|| true
    deb-systemd-invoke stop corepvt.service|| true
    deb-systemd-invoke stop uart1_buad.service|| true
fi

exit 0

